name: sync changes from my-site

on:
  schedule:
    - cron: '0 0 * * 1'  # At 00:00 on Monday
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my-site
        uses: actions/checkout@v2
        with:
          repository: charanravi-online/my-site
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Configure user info
        run: |
          git config user.email "charanravi-online@gmail.com"
          git config user.name "R Charan"

      - name: Fetch changes from my-site
        run: |
          git remote add upstream https://github.com/charanravi-online/my-site.git || true
          git fetch upstream

      - name: Checkout specific contents of the public folder
        run: |
          git checkout upstream/main -- public/*
          # This will sync only the contents inside the public folder

      - name: Commit changes
        run: |
          git add .
          git commit -m "Sync public folder contents from my-site repository"
          git push origin main
